### ISSUE TITLE
Some bugs and code smells fixed 

### ISSUE THREAD

**Issue by tothattila97** [BME-MIT-IET/Csipetcsapat-iet-2018#2]
#### Fixed bugs and code smells

1. StackedBarChartFragment.java,  sum can't be zero  #Line387 
2. FileUtils.java, removed unused import and use try-finally to close stream object #Line6 and #Line26-30
3. MigrationHelper.java, use finally to close the resource #Line1569
4. CalculatorEditText.java, add nested comment and use BigDecimal.valueOf instead of new BigDecimal #Line267
5. ReportType.java and ScheduledActionsActivity.java, added default case to switch statement #Line48 and #Line 114
6. Money.java, only the sign of the result should be examined #Line425
7. GnuCashApplication.java,  cast one operand to long in a multiplication #Line79

**Comment by tothattila97** [comment]
Reopened for review @zsonglorman

**Comment by zsonglorman** [comment]
Run code analysis via SonarQube before and after the fixes, added screenshots to the repo and WIKI.
I checked the fixed bugs, most are OK.
Some fixes introduced new bugs, I fixed these and also some others.
Several bugs were related to inappropriate stream closing, I fixed these with try-with-resources statements.
Pull request will be accepted (merge these fixes into master).
