### ISSUE TITLE
Kézi kódátvizsgálás

### ISSUE THREAD

**Issue by timii111** [BME-MIT-IET/Csipetcsapat-iet-2018#4]
Átvizsgálom a kódot, a wikioldalra kerül majd az eredménye.

**Comment by timii111** [comment]
Felkerült a vizsgálati eredmény

**Comment by Leslietheone** [comment]
Átnéztem a leírtakat. Jogosnak tartom az észrevételeidet.
A TODO-k megvalósítását érzem a fontosabb jövőbeli feladatnak, utána pedig az átláthatóság javítását.
A vizsgálat szempontjából teljesítettnek látom ezt a témát, így lezárom.
