### ISSUE TITLE
Increase test coverage

### ISSUE THREAD

**Issue by zsonglorman** [BME-MIT-IET/Csipetcsapat-iet-2018#5]
The goal is to examine current test coverage with Jacoco, then write more unit tests to increase the test coverage.

**Comment by zsonglorman** [comment]
Created several unit tests to increase test coverage for:
- stripCurrencyFormatting method in TransactionFormFragment
- Budget class in model package.

**Comment by zsonglorman** [comment]
@tothattila97 Please review tests, comment, and accept the referenced pull request

**Comment by tothattila97** [comment]
I reviewed the tests, they are looks correct, I'll accept your pull request.
I also checked your bug fixes about the not closed stream resources and that are OK.
