### ISSUE TITLE
Manuális tesztek

### ISSUE THREAD

**Issue by Leslietheone** [BME-MIT-IET/Csipetcsapat-iet-2018#7]
Manuális teszteknek vetettem alá a programot.
A tapasztalt eredmények felkerültek a wiki oldalra.

**Comment by timii111** [comment]
Átnéztem a tesztleírásokat.
Nagyon jó, hogy képeken látjuk az eredményt és hogy gif-en a tapasztalt hibát.
Sajnálatos, hogy rosszul működik az alkalmazás, de jelenleg nem feladatunk minden hibát kijavítani.
Az issue-t így lezárom, a teszt jó.
